version: "3"

services:
  postgresql:
    image: library/postgres:12
    env_file: .env
    volumes:
    - ./postgres-docker/pgdata:/var/lib/postgresql/data/pgdata
    expose:
      - 5432

  application:
    build: ./
    env_file: .env
    command: bash -c "while !</dev/tcp/postgresql/5432; do sleep 1; done && python bot.py"
    depends_on:
      - postgresql
    expose:
      - 8000

